Portafolio/Examen2/nfl_pr/core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    
]

Portafolio/Examen2/nfl_pr/home/urls.py
from django.urls import path
from home import views
from .views import (
    CityWithTeams, TeamStadium,
    CityTeams,
)

app_name = "home"
urlpatterns = [

   path('ciudad/', views.CityIndex.as_view(), name='ciudadindex'),
   path('ciudad/new/', views.NewCiudad.as_view(), name='ciudad_new'),
   path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='ciudad_detail'),
   path('ciudad/<int:pk>/edit/', views.UpdateCiudad.as_view(), name='ciudad_edit'),
   path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='ciudad_delete'),

   path('estadio/', views.StadiumIndex.as_view(), name='estadioindex'),
   path('estadio/new/', views.NewEstadio.as_view(), name='estadio_new'),
   path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='estadio_detail'),
   path('estadio/<int:pk>/edit/', views.UpdateEstadio.as_view(), name='estadio_edit'),
   path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='estadio_delete'),
   
   path('equipo/', views.TeamIndex.as_view(), name='equipoindex'),
   path('equipo/', views.EquipoIndex.as_view(), name="teamindex"),
   path('equipo/new/', views.NewEquipo.as_view(), name='equipo_new'),
   path('equipo/<int:pk>/', views.DetailEquipo.as_view(), name='equipo_detail'),
   path('equipo/<int:pk>/edit/', views.UpdateEquipo.as_view(), name='equipo_edit'),
   path('equipo/<int:pk>/delete/', views.DeleteEquipo.as_view(), name='equipo_delete'),


   path('', views.Index.as_view(), name='index'),

   path('equipo/citywithteams/', CityWithTeams.as_view(), name='cityWithTeams'),
   path('equipo/teamstadium/', TeamStadium.as_view(), name='teamsStadium'),
   path('equipo/cityteams/', CityTeams.as_view(), name='cityTeams'),
]

Portafolio/Examen2/nfl_pr/nfl_pr/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

Portafolio/Examen2/nfl_pr/templates/base/equipoindex.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <title>Administración de Equipos de la NFL</title>
  <style>
      body {
          background-color: #f0f0f0;
      }

  </style>
</head>
<body>
  <div class="container">
    <!-- NAV BAR -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">NFL TEAMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home:equipoindex' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:ciudadindex' %}">Ciudades</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:estadioindex' %}">Estadios</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Opciones
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'home:cteams' %}">Ciudades con Equipos</a></li>
                <li><a class="dropdown-item" href="{% url 'home:estadioe' %}">Equipos Por Estadios</a></li>
                <li><a class="dropdown-item" href="{% url 'home:cequipos' %}">Ciudades por equipos</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">:V</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    
      <h1>Administración de Equipos de la NFL</h1>
      <p><strong>Bienvenido al panel de administración de equipos de la NFL</strong></p>
      <p>Esta plataforma te permite gestionar y administrar los equipos que forman parte de la National Football League. Aquí puedes realizar una variedad de tareas relacionadas con los equipos, sus ciudades, estadios y jugadores.</p>

      <p><strong>Funcionalidades</strong></p>
      <ul>
          <li>Añadir un nuevo equipo a la liga.</li>
          <li>Actualizar información sobre equipos existentes, como su nombre, ciudad y año de fundación.</li>
          <li>Gestionar la información de las ciudades a las que pertenecen los equipos.</li>
          <li>Administrar los estadios donde los equipos juegan sus partidos.</li>
      </ul>

      <p><strong>¡Comienza a Administrar!</strong></p>
      <p>Explora las diferentes secciones de la plataforma para realizar las tareas de administración necesarias para mantener la información de los equipos de la NFL actualizada. Tu contribución es fundamental para mantener viva la pasión y la emoción del fútbol americano en todo el país.</p>
  </div>


    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
</body>
</html>